version: '3'
services:
  product-web-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      GRAPH_QL_API: http://product-graph-ql-server:3001/graphql
    ports:
      - "3000:3000"
    networks:
      - ms-product
  product-graph-ql-server:
    image: chrismns/tech-test-mock-server:0.1.0
    ports:
      - "3001:3001"
    networks:
      - ms-product

networks:
  ms-product:
    driver: bridge